image: python:3.6

variables:
  PYTHON_TAG: py3
  ABI_TAG: none
  PLATFORM_TAG: any
  PACKAGE_EXTENSION: whl

stages:
  - unitTests
  - build
  - deploy
  - test

unitTests:
  stage: unitTests
  script:
    - export LC_ALL=C.UTF-8
    - export LANG=C.UTF-8
    - pip3 install pipenv
    - pipenv sync --dev
    - pipenv run python -V
    - pipenv run tox
  only:
    - branches
    - tags

build:
  stage: build
  script:
    # Get version. Variable CI_COMMIT_TAG is set only when tag was pushed.
    - export VERSION=$(if [[ "$CI_COMMIT_TAG" == "" ]]; then echo 0.0.0; else echo $CI_COMMIT_TAG | cut -c 2-; fi)
    - python3 setup.py setopt --command=metadata --option=version --set-value=$VERSION
    - echo VERSION=$VERSION
    # Get package filename
    - export WHEEL_NAME=$(python3 setup.py --name | tr '-' '_')
    - export PACKAGE=$WHEEL_NAME-$VERSION-$PYTHON_TAG-$ABI_TAG-$PLATFORM_TAG.$PACKAGE_EXTENSION
    - echo PACKAGE=$PACKAGE
    - python3 setup.py bdist_wheel
    - echo $PACKAGE > dist/.package-name
  only:
    - branches
    - tags
  artifacts:
    paths:
      - dist
    expire_in: 1 day

deploy:
  stage: deploy
  variables:
    TWINE_PASSWORD: '$CI_CUSTOM_REGISTRY_PASSWORD'
    TWINE_USERNAME: '$CI_CUSTOM_REGISTRY_USER'
  script:
    - export PACKAGE=$(cat dist/.package-name)
    - pip3 install twine
    - python3 -m twine upload --repository-url $KYPO_PYPI_UPLOAD_URL dist/$PACKAGE
  dependencies:
    - build
  only:
    - tags

sast:
  stage: test
  variables:
    SAST_DEFAULT_ANALYZERS: bandit
    DS_DEFAULT_ANALYZERS: gemnasium-python

include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Secret-Detection.gitlab-ci.yml
  - template: Dependency-Scanning.gitlab-ci.yml

