[tox]
parallel_show_output = True
envlist = pre-commit, pylint, bandit, audit, pytest

[testenv]

[testenv:pylint]
dependency_groups = lint
commands = pylint crczp tests --output-format=colorized --fail-under=9.5

[testenv:bandit]
dependency_groups = security
commands = bandit -r crczp

[testenv:audit]
dependency_groups = security
commands = pip-audit --progress-spinner=off

[testenv:pytest]
runner = uv-venv-lock-runner
dependency_groups = test
commands = pytest
testpaths = tests
markers = integration

# pre-commit covers ruff lint, ruff format, mypy
[testenv:pre-commit]
dependency_groups = dev
commands = pre-commit run --all-files --show-diff-on-failure